"""add status column to scenarios

Revision ID: 8b25e0a1bbde
Revises: 2f118cfadda2
Create Date: 2026-03-11 12:40:07.179229

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8b25e0a1bbde'
down_revision: Union[str, None] = '2f118cfadda2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scenarios', sa.Column('status', sa.Integer(), nullable=False, server_default=sa.text("1")))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scenarios', 'status')
    # ### end Alembic commands ###
